# Generated by Django 2.2.12 on 2020-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=20)),
                ('horizontal_velocity', models.IntegerField()),
                ('vertical_velocity', models.IntegerField()),
                ('distance_top', models.IntegerField()),
                ('distance_left', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
