# Generated by Django 2.2.12 on 2020-07-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourses',
            old_name='coursename',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='allcourses',
            old_name='insname',
            new_name='instructor_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='couse',
            new_name='course',
        ),
    ]
