# Generated by Django 2.2.12 on 2020-07-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200702_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allcourses',
            new_name='Course',
        ),
    ]
